# Generated by Django 2.2.7 on 2020-03-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200310_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='link_yt',
            field=models.CharField(max_length=200),
        ),
    ]
