# Generated by Django 2.2.7 on 2020-03-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200310_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='release_date',
        ),
    ]
